// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/trips": {
            "get": {
                "description": "Получение списка поездок пользователя",
                "consumes": [
                    "application/json"
                ],
                "summary": "GetTrips",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID of user",
                        "name": "user_id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/trips/{trip_id}": {
            "get": {
                "description": "Получение поездки по ID",
                "consumes": [
                    "application/json"
                ],
                "summary": "GetTripByTripId",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID of user",
                        "name": "user_id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID of trip",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/trips/{trip_id}/accept": {
            "post": {
                "description": "Принятие поездки водителем",
                "consumes": [
                    "application/json"
                ],
                "summary": "AcceptTrip",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID of user",
                        "name": "user_id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID of trip",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/trips/{trip_id}/cancel": {
            "post": {
                "description": "Отмена поездки водителем",
                "consumes": [
                    "application/json"
                ],
                "summary": "CancelTrip",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID of user",
                        "name": "user_id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID of trip",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reason of cancel",
                        "name": "reason",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/trips/{trip_id}/end": {
            "post": {
                "description": "Окончание поездки водителем",
                "consumes": [
                    "application/json"
                ],
                "summary": "EndTrip",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID of user",
                        "name": "user_id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID of trip",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/trips/{trip_id}/start": {
            "post": {
                "description": "Начало поездки водителем",
                "consumes": [
                    "application/json"
                ],
                "summary": "StartTrip",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID of user",
                        "name": "user_id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID of trip",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Driver service",
	Description:      "This is a driver service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
